bg: green-100
title: Build automation that doesn't trip you up.
text: |
  Too often bad automation just gets in the way. From orchestrating lead flows to email and SMS touchpoints, the right systems can guide your lead to onboarding with finesse.
icon: Workflow.svg
alt: Worflow automation diagram
